version: "3.8"
services:
  copter:
    build: .
  plane:
    environment:
      - SITL_EXE=arduplane
      - SITL_OPTS=--model=plane --defaults=/home/pilot/ardupilot/Tools/autotest/default_params/plane.parm
    build: .
