version: "3.8"
services:
  copter:
    environment:
      - MAVLINK_HOSTNAME=mavgw
    image: arthurrichards77/ardupilot-sitl-docker:v3
  mavgw:
    image: arthurrichards77/mavrouter:v1
    container_name: mavgw
    command: mavlink-routerd 0.0.0.0:14553
    ports:
      - "5760:5760"
